# -*- coding: utf-8 -*-
"""
@desc: 福建省政府采购网
@version: python3
@author: xm
@time: 2023/06/29
"""
import datetime
import json
import re
import time

import ddddocr  ## pip install ddddocr
import requests
import scrapy

from bs4 import BeautifulSoup

from bid_scrapy_project.common.common import get_md5
from bid_scrapy_project.items import GovernmentProcurementItem


class FujianCgwSpider(scrapy.Spider):
    name = "fujian_cgw"

    # allowed_domains = ['zfcg.czt.fujian.gov.cn']
    # start_urls = ['http://zfcg.czt.fujian.gov.cn/']
    def __init__(self):
        self.webName = "福建省政府采购网"
        self.webUrl = "http://zfcg.czt.fujian.gov.cn/"
        self.province = "福建省"
        self.citys = [
            {
                "id": "C4697AC1D0DB47A596949BA3FD1197E6",
                "regionCode": "350001",
                "name": "省本级",
                "parentId": "",
                "isLeaf": "0",
                "levelNum": "1",
                "enabled": "1",
                "remark": "http://zfcg.czt.fujian.gov.cn/",
                "sysAppId": "00001",
                "setYear": "2017",
                "createDate": "2017-04-19 00:00:00",
                "createUser": "sys",
                "latestModifyDate": "2017-04-19 00:00:00",
                "latestModifyUser": "sys",
                "rId": "",
                "rName": "",
            },
            {
                "id": "54fcc827-edd5-11eb-81d6-fa163e098fbb",
                "regionCode": "350190",
                "name": "平潭综合实验区",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.pingtan.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
            },
            {
                "id": "54fcc827-edd5-11eb-81d6-fa163e098fbb",
                "regionCode": "350101",
                "name": "福州市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.fuzhou.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1263",
                        "regionCode": "350102",
                        "name": "鼓楼区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 鼓楼区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1264",
                        "regionCode": "350103",
                        "name": "台江区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 台江区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1265",
                        "regionCode": "350104",
                        "name": "仓山区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 仓山区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1266",
                        "regionCode": "350105",
                        "name": "马尾区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 马尾区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1267",
                        "regionCode": "350111",
                        "name": "晋安区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 晋安区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1268",
                        "regionCode": "350121",
                        "name": "闽侯县",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 闽侯县",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1269",
                        "regionCode": "350122",
                        "name": "连江县",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 连江县",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1270",
                        "regionCode": "350123",
                        "name": "罗源县",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 罗源县",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1270",
                        "regionCode": "350124",
                        "name": "闽清县",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 闽清县",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1270",
                        "regionCode": "350125",
                        "name": "永泰县",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 永泰县",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1270",
                        "regionCode": "350181",
                        "name": "福清市",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 福清市",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1270",
                        "regionCode": "350182",
                        "name": "长乐区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 长乐区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                    {
                        "id": "1270",
                        "regionCode": "350191",
                        "name": "高新区",
                        "parentId": "1261",
                        "leaf": "1",
                        "remark": "http://zfcg.fuzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 福州市 高新区",
                        "province": "福建省 ",
                        "localCity": "福州市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbbee",
                "regionCode": "350201",
                "name": "厦门市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://ccgp-xiamen.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1278",
                        "regionCode": "350203",
                        "name": "思明区",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 思明区",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                    {
                        "id": "1279",
                        "regionCode": "350205",
                        "name": "海沧区",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 海沧区",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                    {
                        "id": "1280",
                        "regionCode": "350206",
                        "name": "湖里区",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 湖里区",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                    {
                        "id": "1281",
                        "regionCode": "350211",
                        "name": "集美区",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 集美区",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                    {
                        "id": "1282",
                        "regionCode": "350212",
                        "name": "同安区",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 同安区",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                    {
                        "id": "1283",
                        "regionCode": "350213",
                        "name": "翔安区",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 翔安区",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                    {
                        "id": "1283",
                        "regionCode": "350222",
                        "name": "火炬管委会",
                        "parentId": "1276",
                        "leaf": "1",
                        "remark": "http://ccgp-xiamen.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 厦门市 火炬管委会",
                        "province": "福建省 ",
                        "localCity": "厦门市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbbaa",
                "regionCode": "350301",
                "name": "莆田市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://www.ptzfcg.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1286",
                        "regionCode": "350302",
                        "name": "城厢区",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 城厢区",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                    {
                        "id": "1287",
                        "regionCode": "350303",
                        "name": "涵江区",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 涵江区",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                    {
                        "id": "1288",
                        "regionCode": "350304",
                        "name": "荔城区",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 荔城区",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                    {
                        "id": "1289",
                        "regionCode": "350305",
                        "name": "秀屿区",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 秀屿区",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                    {
                        "id": "1289",
                        "regionCode": "350306",
                        "name": "湄洲岛管委会",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 湄洲岛管委会",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                    {
                        "id": "1289",
                        "regionCode": "350307",
                        "name": "北岸管委会",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 北岸管委会",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                    {
                        "id": "1290",
                        "regionCode": "350322",
                        "name": "仙游县",
                        "parentId": "1284",
                        "leaf": "1",
                        "remark": "http://www.ptzfcg.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 莆田市 仙游县",
                        "province": "福建省 ",
                        "localCity": "莆田市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbb1",
                "regionCode": "350401",
                "name": "三明市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.cz.sm.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1293",
                        "regionCode": "350402",
                        "name": "梅列区",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 梅列区",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1294",
                        "regionCode": "350403",
                        "name": "三元区",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 三元区",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1295",
                        "regionCode": "350421",
                        "name": "明溪县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 明溪县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1296",
                        "regionCode": "350423",
                        "name": "清流县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 清流县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1297",
                        "regionCode": "350424",
                        "name": "宁化县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 宁化县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1298",
                        "regionCode": "350425",
                        "name": "大田县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 大田县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1299",
                        "regionCode": "350426",
                        "name": "尤溪县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 尤溪县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1300",
                        "regionCode": "350427",
                        "name": "沙县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 沙县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1300",
                        "regionCode": "350428",
                        "name": "将乐县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 将乐县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1300",
                        "regionCode": "350429",
                        "name": "泰宁县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 泰宁县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1300",
                        "regionCode": "350430",
                        "name": "建宁县",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 建宁县",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                    {
                        "id": "1300",
                        "regionCode": "350481",
                        "name": "永安市",
                        "parentId": "1291",
                        "leaf": "1",
                        "remark": "http://zfcg.cz.sm.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 三明市 永安市",
                        "province": "福建省 ",
                        "localCity": "三明市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbb2",
                "regionCode": "350501",
                "name": "泉州市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.quanzhou.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1307",
                        "regionCode": "350502",
                        "name": "鲤城区",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 鲤城区",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1308",
                        "regionCode": "350503",
                        "name": "丰泽区",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 丰泽区",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1309",
                        "regionCode": "350504",
                        "name": "洛江区",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 洛江区",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1310",
                        "regionCode": "350505",
                        "name": "泉港区",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 泉港区",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1311",
                        "regionCode": "350521",
                        "name": "惠安县",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 惠安县",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1312",
                        "regionCode": "350524",
                        "name": "安溪县",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 安溪县",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1313",
                        "regionCode": "350525",
                        "name": "永春县",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 永春县",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1314",
                        "regionCode": "350526",
                        "name": "德化县",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 德化县",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1314",
                        "regionCode": "350581",
                        "name": "石狮市",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 石狮市",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1314",
                        "regionCode": "350582",
                        "name": "晋江市",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 晋江市",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1314",
                        "regionCode": "350583",
                        "name": "南安市",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 南安市",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                    {
                        "id": "1314",
                        "regionCode": "350590",
                        "name": "泉州台商投资区",
                        "parentId": "1305",
                        "leaf": "1",
                        "remark": "http://zfcg.quanzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 泉州市 泉州台商投资区",
                        "province": "福建省 ",
                        "localCity": "泉州市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbb3",
                "regionCode": "350601",
                "name": "漳州市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1321",
                        "regionCode": "350602",
                        "name": "芗城区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 芗城区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1322",
                        "regionCode": "350603",
                        "name": "龙文区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 龙文区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1322",
                        "regionCode": "350604",
                        "name": "漳州开发区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 漳州开发区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1323",
                        "regionCode": "350622",
                        "name": "云霄县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 云霄县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1324",
                        "regionCode": "350623",
                        "name": "漳浦县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 漳浦县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1325",
                        "regionCode": "350624",
                        "name": "诏安县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 诏安县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1326",
                        "regionCode": "350625",
                        "name": "长泰区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 长泰县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1327",
                        "regionCode": "350626",
                        "name": "东山县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 东山县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350627",
                        "name": "南靖县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 南靖县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350628",
                        "name": "平和县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 平和县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350629",
                        "name": "华安县",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 华安县",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350630",
                        "name": "常山开发区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 常山开发区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350681",
                        "name": "龙海区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 龙海区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350690",
                        "name": "漳州台商投资区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 漳州台商投资区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350691",
                        "name": "漳州高新技术开发区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 漳州台商投资区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                    {
                        "id": "1328",
                        "regionCode": "350692",
                        "name": "古雷港经济开发区",
                        "parentId": "1319",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.zhangzhou.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 漳州市 漳州台商投资区",
                        "province": "福建省 ",
                        "localCity": "漳州市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbb4",
                "regionCode": "350701",
                "name": "南平市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.np.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1334",
                        "regionCode": "350702",
                        "name": "延平区",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 延平区",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1335",
                        "regionCode": "350703",
                        "name": "建阳区",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 建阳区",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1335",
                        "regionCode": "350721",
                        "name": "顺昌县",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 顺昌县",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1336",
                        "regionCode": "350722",
                        "name": "浦城县",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 浦城县",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1337",
                        "regionCode": "350723",
                        "name": "光泽县",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 光泽县",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1338",
                        "regionCode": "350724",
                        "name": "松溪县",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 松溪县",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1339",
                        "regionCode": "350725",
                        "name": "政和县",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 政和县",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1340",
                        "regionCode": "350781",
                        "name": "邵武市",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 邵武市",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1341",
                        "regionCode": "350782",
                        "name": "武夷山市",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 武夷山市",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                    {
                        "id": "1341",
                        "regionCode": "350783",
                        "name": "建瓯市",
                        "parentId": "1332",
                        "leaf": "1",
                        "remark": "http://zfcg.np.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 南平市 建瓯市",
                        "province": "福建省 ",
                        "localCity": "南平市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbb5",
                "regionCode": "350801",
                "name": "龙岩市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.longyan.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1346",
                        "regionCode": "350802",
                        "name": "新罗区",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 新罗区",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1346",
                        "regionCode": "350803",
                        "name": "开发区",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 开发区",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1347",
                        "regionCode": "350821",
                        "name": "长汀县",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 长汀县",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1348",
                        "regionCode": "350822",
                        "name": "永定县",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 永定县",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1349",
                        "regionCode": "350823",
                        "name": "上杭县",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 上杭县",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1350",
                        "regionCode": "350824",
                        "name": "武平县",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 武平县",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1351",
                        "regionCode": "350825",
                        "name": "连城县",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 连城县",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                    {
                        "id": "1352",
                        "regionCode": "350881",
                        "name": "漳平市",
                        "parentId": "1344",
                        "leaf": "1",
                        "remark": "http://zfcg.longyan.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 龙岩市 漳平市",
                        "province": "福建省 ",
                        "localCity": "龙岩市 ",
                    },
                ],
            },
            {
                "id": "54fcf0f9-edd5-11eb-81d6-fa163e098fbb6",
                "regionCode": "350901",
                "name": "宁德市",
                "parentId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "isLeaf": "0",
                "levelNum": "2",
                "enabled": "1",
                "remark": "http://zfcg.czj.ningde.gov.cn/",
                "sysAppId": "gpc-gpcms",
                "setYear": "2021",
                "createDate": "2021-07-26 13:50:07",
                "createUser": "admin",
                "latestModifyDate": "2021-07-26 13:50:07",
                "latestModifyUser": "admin",
                "rId": "C4697AC1D0DB47A596949BA3FD1197E6",
                "rName": "省本级",
                "children": [
                    {
                        "id": "1355",
                        "regionCode": "350902",
                        "name": "蕉城区",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 蕉城区",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1355",
                        "regionCode": "350903",
                        "name": "东侨区",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 东侨区",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1356",
                        "regionCode": "350921",
                        "name": "霞浦县",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 霞浦县",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1357",
                        "regionCode": "350922",
                        "name": "古田县",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 古田县",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1358",
                        "regionCode": "350923",
                        "name": "屏南县",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 屏南县",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1359",
                        "regionCode": "350924",
                        "name": "寿宁县",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 寿宁县",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1360",
                        "regionCode": "350925",
                        "name": "周宁县",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 周宁县",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1361",
                        "regionCode": "350926",
                        "name": "柘荣县",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 柘荣县",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1362",
                        "regionCode": "350981",
                        "name": "福安市",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 福安市",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                    {
                        "id": "1362",
                        "regionCode": "350982",
                        "name": "福鼎市",
                        "parentId": "1353",
                        "leaf": "1",
                        "remark": "http://zfcg.czj.ningde.gov.cn/",
                        "levelNum": "3",
                        "standard": "1",
                        "enabled": "1",
                        "setYear": "2022",
                        "operateDate": "2019-12-25 20:46:30",
                        "path": "福建省 宁德市 福鼎市",
                        "province": "福建省 ",
                        "localCity": "宁德市 ",
                    },
                ],
            },
        ]
        self.categorys = {
            "单一来源公示": "001051",
            "采购公告": "00101",
            "更正公告": "00103",
            "结果公告": "001021,001022,001023,001024,001025,001026,001029,001004,001006",
            "合同公示": "001054",
            # "网上超市合同公示": "001054",
            "采购意向公开": "59",
            "面向中小企业预留项目执行情况公告": "001062",
        }
        #"公开招标": 1, "邀请招标": 2, "竞争性谈判": 3, "询价": 4, "单一来源": 5, "竞争性磋商": 6, "其他": 9,
        self.opts = {"全部": "-1"}
        self.verifyCode = None
        self.page = 2
    def start_requests(self):
        """
        url 参数说明：
            regionCode 城市id
            noticeType 公告类型
            verifyCode：验证码
            purchaseManner：采购方式
            purchaseManner:合同公示 9 网上超市合同公示！9
        """
        # 循环城市
        for city in self.citys:
            regionCode = city.get("regionCode")  ##城市id
            cityName = city.get("name")  # 城市name
            rName = city.get("rName")  ##上级
            children = city.get("children")
            remark = city.get("remark")  ## 域名
            # 图片的域名会跟着数据的变动而变动
            try:
                self.verifyCode = self.ocr_num(remark)  ##差不多半小时过期  设置28分钟重新获取一次
            except:
                continue
            ##省 市
            for category, categoryid in self.categorys.items():
                for opt, opt_id in self.opts.items():
                    for page in range(1, self.page):
                        # https://zfcg.czt.fujian.gov.cn/freecms/rest/v1/notice/selectInfoMoreChannel.do?&siteId=d36a6e8b-4363-4b52-a00b-79ca47033923&channel=f582600e-065d-4f35-8966-48a33fa93863&currPage=1&pageSize=10&noticeType=001051&regionCode=350101&purchaseManner=1&title=&verifyCode=0952&openTenderCode=&purchaser=&agency=&purchaseNature=&operationStartTime=&operationEndTime=&selectTimeName=noticeTime&cityOrArea=
                        listUrl = "{domain}freecms/rest/v1/notice/selectInfoMoreChannel.do?&siteId=d36a6e8b-4363-4b52-a00b-79ca47033923&channel=f582600e-065d-4f35-8966-48a33fa93863&currPage={page}&pageSize=10&noticeType={noticeType}&regionCode={regionCode}&purchaseManner={purchaseManner}&title=&verifyCode={verifyCode}&openTenderCode=&purchaser=&agency=&purchaseNature=&operationStartTime=&operationEndTime=&selectTimeName=noticeTime&cityOrArea=".format(
                            noticeType=categoryid,
                            regionCode=regionCode,
                            purchaseManner=opt_id,
                            verifyCode=self.verifyCode,
                            domain=remark,
                            page=page
                        )
                        # items = {"po_category": category, "po_info_type": opt}
                        items = {"po_info_type": category}
                        if not "省本级" in cityName:
                            items["po_city"] = cityName
                        yield scrapy.Request(
                            listUrl, self.parse, meta={"items": items, "page": 1, "domain": remark, "num":0, "verifyCode":self.verifyCode}, dont_filter=True
                        )
            ##区
            # if children:
            #     for child in children:
            #         countyname = child.get("name")
            #         county_id = child.get("regionCode")
            #         remark_child = child.get("remark")  ## 域名
            #
            #         for category, categoryid in self.categorys.items():
            #             for opt, opt_id in self.opts.items():
            #                 listUrl_child = "{domain}freecms/rest/v1/notice/selectInfoMoreChannel.do?&siteId=d36a6e8b-4363-4b52-a00b-79ca47033923&channel=f582600e-065d-4f35-8966-48a33fa93863&currPage=1&pageSize=10&noticeType={noticeType}&regionCode={regionCode}&purchaseManner={purchaseManner}&title=&verifyCode={verifyCode}&openTenderCode=&purchaser=&agency=&purchaseNature=&operationStartTime=&operationEndTime=&selectTimeName=noticeTime&cityOrArea=".format(
            #                     noticeType=categoryid,
            #                     regionCode=county_id,
            #                     purchaseManner=opt_id,
            #                     verifyCode=self.verifyCode,
            #                     domain=remark_child,
            #                     dont_filter=True,
            #                 )
            #                 # items_child = {
            #                 #     "po_category": category,
            #                 #     "po_info_type": opt,
            #                 #     "po_county": countyname,
            #                 # }
            #                 items_child = {
            #                     "po_info_type": category,
            #                     "po_county": countyname,
            #                 }
            #                 if not "省本级" in cityName:
            #                     items_child["po_city"] = cityName
            #                 yield scrapy.Request(
            #                     listUrl_child,
            #                     callback=self.parse,
            #                     meta={"items": items_child, "page": 1, "domain": remark},
            #                     dont_filter=True,
            #                 )

    def parse(self, response):
        itmes_info = response.meta["items"]
        jsonDict = json.loads(response.text)
        flag = True
        msg = jsonDict.get("msg")
        if "验证码错误" in msg:
            ##出问题后重新访问 重新设置验证码
            print("验证码错误重新获取")
            num = response.meta['num']
            num +=1
            print("重试次数", num)
            if num > 5:
                return
            verifyCode = self.ocr_num(response.meta["domain"])
            items_num = {
                "num":num,
                "items":response.meta['items'],
                "page": response.meta['page'], "domain": response.meta['domain']
            }
            url = response.request.url.replace(f"verifyCode={str(response.meta['verifyCode'])}&", f"verifyCode={str(verifyCode)}&")
            yield scrapy.Request(url, callback=self.parse, meta=items_num, dont_filter=True)
        else:
            datas = jsonDict.get("data")
            if not datas:
                print("此类别没有数据", itmes_info)
                return
            for data in datas:
                pageurl = data.get("pageurl")
                pageurl = response.urljoin(pageurl)
                title = data.get("title")
                noticeTime = data.get("noticeTime")  ##发布时间
                ##判断是否超过两天 超过两天就不在访问下一页
                timeNow = datetime.datetime.now()  ###现在的时间
                pdate = datetime.datetime.strptime(noticeTime, "%Y-%m-%d %H:%M:%S")
                if abs((timeNow - pdate).days) > 2:  # 判断时间间隔天数
                    flag = False
                items = {}
                po_id = get_md5(pageurl)
                items["po_id"] = po_id
                items["bid_url"] = pageurl
                items["po_province"] = self.province
                items["po_city"] = itmes_info.get("po_city")
                items["po_county"] = itmes_info.get("po_county")
                items["po_category"] = "政府采购"
                items["po_info_type"] = itmes_info.get("po_info_type")
                items["po_public_time"] = noticeTime
                items["bo_name"] = title
                yield scrapy.Request(pageurl, callback=self.contentParse, meta={"items": items})


    def contentParse(self, response):
        """
        获取内容
        """
        content_html = response.css("#content").get()
        contents = response.css("#content *::text").extract()
        content = "".join(x.strip() for x in contents)
        items = GovernmentProcurementItem()
        items.update(response.meta.get("items"))
        items["website_name"] = self.webName
        items["website_url"] = self.webUrl
        items["create_datetime"] = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(int(time.time())))
        # print(items)
        items["po_content"] = content
        items["po_html_con"] = str(content_html)
        # items["po_json_data"] = response.text
        yield items

    def ocr_num(self, domain):
        """
        根据链接获取到返回的验证码图片 并进行识别
        """
        # url = "https://zfcg.czt.fujian.gov.cn/freecms/verify/verifyCode.do?createTypeFlag=n&name=notice&d{}".format(
        #     int(time.time() * 1000)
        # )
        url = "{domain}freecms/verify/verifyCode.do?createTypeFlag=n&name=notice&d{nowtime}".format(
            domain=domain, nowtime=int(time.time() * 1000)
        )
        r = requests.get(url)
        ocr = ddddocr.DdddOcr()

        res = ocr.classification(r.content)
        return res
