# -*- coding: utf-8 -*-
"""
Created on 2023-06-12 11:20:55
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongTaianSeedTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_taian_seed_task 1
    """

    __table_name__ = "t_zx_tendering_shandong_taian_seed_task"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.url = kwargs.get('url')
        self.post_url = kwargs.get('post_url')
        # self.state = kwargs.get('state')
        self.data_id = kwargs.get('data_id')
        self.page = kwargs.get('page')
        self.one_title = kwargs.get('one_title')
        self.two_title = kwargs.get('two_title')
        # self.update_time = kwargs.get('update_time')
        # self.create_time = kwargs.get('create_time')
