# -*- coding: utf-8 -*-
"""
Created on 2023-06-12 15:40:35
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongWeihaiListTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_weihai_list_task 1
    """

    __table_name__ = "t_zx_tendering_shandong_weihai_list_task"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')  # id主键
        self.categorynum = kwargs.get('categorynum')
        self.url = kwargs.get('url')
        # self.state = kwargs.get('state')
        self.data_id = kwargs.get('data_id')
        self.page = kwargs.get('page')
        self.infotype = kwargs.get('infotype')
        self.one_title = kwargs.get('one_title')
        self.two_title = kwargs.get('two_title')
        self.infourl = kwargs.get('infourl')
        self.strcomment = kwargs.get('strcomment')
        self.infoid = kwargs.get('infoid')
        self.titletype = kwargs.get('titletype')
        self.title = kwargs.get('title')
        self.urlname = kwargs.get('urlname')
        self.infodate = kwargs.get('infodate')
        self.customtitle = kwargs.get('customtitle')
        self.shixiao = kwargs.get('shixiao')
        self.recommend = kwargs.get('recommend')
        # self.crawl_time = kwargs.get('crawl_time')  # 采集时间
        # self.update_time = kwargs.get('update_time')
