# -*- coding: utf-8 -*-
"""
Created on 2023-06-12 14:32:46
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongTananListTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_tanan_list_and_details_info 1
    """

    __table_name__ = "t_zx_tendering_shandong_tanan_list_task"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')  # id主键
        self.categorynum = kwargs.get('categorynum')
        self.url = kwargs.get('url')
        self.data_id = kwargs.get('data_id')
        self.page = kwargs.get('page')
        self.titlenew = kwargs.get('titlenew')
        self.one_title = kwargs.get('one_title')
        self.two_title = kwargs.get('two_title')
        self.areaname = kwargs.get('areaname')
        self.sysclicktimes = kwargs.get('sysclicktimes')
        self.title = kwargs.get('title')
        self.areacode = kwargs.get('areacode')
        self.content = kwargs.get('content')
        self.webdate = kwargs.get('webdate')
        self.highlight = kwargs.get('highlight')
        self.score = kwargs.get('score')
        self.customtitle = kwargs.get('customtitle')
        self.syscategory = kwargs.get('syscategory')
        self.syscollectguid = kwargs.get('syscollectguid')
        self.relationguid = kwargs.get('relationguid')
        self.linkurl = kwargs.get('linkurl')  # 详情URl
        self.sysscore = kwargs.get('sysscore')
        self.infodate = kwargs.get('infodate')
        # self.crawl_time = kwargs.get('crawl_time')  # 采集时间
        # self.update_time = kwargs.get('update_time')
