# -*- coding: utf-8 -*-
"""
Created on 2023-06-12 16:06:59
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongWeihaiSeedTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_weihai_seed_task
    """

    __table_name__ = "t_zx_tendering_shandong_weihai_seed_task"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.url = None
        self.post_url = None
        # self.state = 0
        self.data_id = 0
        self.page = 0
        self.one_title = None
        self.two_title = None
        # self.update_time = None
        # self.create_time = None
