# -*- coding: utf-8 -*-
"""
Created on 2023-06-12 09:13:56
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongJiningDetailsInfoItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_jining_details_info 1
    """

    __table_name__ = "t_zx_tendering_shandong_jining_details_info"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.list_id = kwargs.get('list_id')
        self.category_code = kwargs.get('category_code')
        self.details_content = kwargs.get('details_content')
        # self.update_time = kwargs.get('update_time')
        # self.create_time = kwargs.get('create_time')
