# -*- coding: utf-8 -*-
"""
Created on 2023-06-09 17:12:27
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongJiningListTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_jining_list_task 1
    """

    __table_name__ = "t_zx_tendering_shandong_jining_list_task"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')  # id主键
        self.category_code = kwargs.get('category_code')
        self.url = kwargs.get('url')
        self.state = kwargs.get('state')
        self.data_id = kwargs.get('data_id')
        self.page = kwargs.get('page')
        self.release_date = kwargs.get('release_date')
        self.one_title = kwargs.get('one_title')
        self.two_title = kwargs.get('two_title')
        self.title = kwargs.get('title')
        self.creation_time = kwargs.get('creation_time')
        self.last_modification_time = kwargs.get('last_modification_time')
        self.list_id = kwargs.get('list_id')
        # self.crawl_time = kwargs.get('crawl_time')  # 采集时间
        # self.update_time = kwargs.get('update_time')
