# -*- coding: utf-8 -*-
"""
Created on 2023-06-08 15:15:34
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongJiningSeedTaskItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_jining_seed_task 1
    """

    __table_name__ = "t_zx_tendering_shandong_jining_seed_task"

    def __init__(self, *args, **kwargs):
        # self.id = kwargs.get('id')
        self.url = kwargs.get('url')  # URL
        self.post_url = kwargs.get('post_url')  # 请求链接
        self.data_id = kwargs.get('data_id')  # 请求id
        self.page = kwargs.get('page')  # 页数
        self.one_title = kwargs.get('one_title')  # 一级标签
        self.two_title = kwargs.get('two_title')  # 二级标签
        # self.create_time = kwargs.get('create_time')  # 创建时间
        # self.update_time = kwargs.get('update_time')  # 更新时间
