# -*- coding: utf-8 -*-
"""
Created on 2023-06-12 17:40:17
---------
@summary:
---------
@author: zhongxing
"""

from feapder import Item


class TZxTenderingShandongWeihaiDetailsInfoItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_zx_tendering_shandong_weihai_details_info
    """

    __table_name__ = "t_zx_tendering_shandong_weihai_details_info"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.infoid = None
        self.infourl = None
        self.url = None
        self.details_content = None
        # self.update_time = None
        # self.create_time = None
